# Generated by Django 5.2.1 on 2025-05-09 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_evenement', models.DateTimeField()),
                ('lieu', models.CharField(max_length=50)),
                ('nombre_place', models.PositiveIntegerField()),
                ('categorie', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenement_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('capacite_maximale', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='NOne', max_length=50)),
                ('mode_paiement', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard')], default='NOne', max_length=20)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('statut', models.CharField(choices=[('confirmée', 'Confirmée'), ('en cours', 'En cours'), ('annulée', 'Annulée')], default='en cours', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.CharField(blank=True, max_length=7, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('bilet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.billet')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_place_reservee', models.PositiveIntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('statut', models.CharField(choices=[('confirmée', 'Confirmée'), ('en cours', 'En cours'), ('annulée', 'Annulée')], default='en cours', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evenement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.evenement')),
            ],
        ),
        migrations.AddField(
            model_name='billet',
            name='num_reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.reservation'),
        ),
    ]
